language: ruby
env:
  matrix:
  - RACK_ENV=development
sudo: false
rvm:
- 2.6.0
services:
- docker
before_install:
- ./bin/pull_worker.sh
deploy:
  provider: rubygems
  api_key:
    secure: zRhMVxKawV0F2yBWLSOaYPsofUKLmZe68ZwtpnLj25eWpdQ7Qt1M3C/0D/Nxs3B4rIB1YJeMqia1wkDz+EQN/C/3CEGdoHZD6FKcr47mD1WC6wzCgd4wRjbIjqorw4k9sDMmneEQAdLK7eRd+fUG+zbOv0Z8I9V2U2d0yZo9VNzLT81vyQU2iyTDYv8/i0pkhXP2hTbWk99dCu2Cm8Vp+D76KHNKSeafRoUzPSJmFI27phgSnyLnU+HLDX2ZCxyc8l3iYkfSAu63+yv44mbfZlDUPgkENpNL6JamxfCKNC4bC5IziURPVod+GoBKaTMx1004saI7P9EtD4hOcGaZj0MBmkZRzp0oH8KvMH7pWyCn8gZ/64fXfHdqOjQ1K4czWZNFmTfr6r5EFDboIvIeQY5LR5K60gVWzeU0Q3N7medK6ritQqWTQ/8Xurj6dh1XhtD/Kh8bhc8XqZLMUTUYUS31mH1XeubckE+vZXFX9Bq2hU2+Wlq2HgDtQvl7dUXgb1i8lknXO2g+3KfEsYpmKSvW9tXN3oH0Cy7dob2shQaobL+DDoDS3HU50k1eK1K0Al3P+f7lLkRqhsEiIqheIg4YSELa9qnAtH47pQLkoJ8ljPlCvPouFszx99Yx+ss3NWvBuw36KAWzbWElST3pjnJ6g/SDKBvu3D8mwpnfe00=
  gem: mumuki-bash-runner
  on:
    tags: true
    repo: mumuki/mumuki-bash-runner
